serenity.project.name = Sara3 - Automatizacion Cases
serenity.logging = VERBOSE
serenity.take.screenshots = AFTER_EACH_STEP

webdriver.driver = chrome
webdriver.base.url = https://asistenciaapp.kit.sura-konecta.com
chrome.switches = --start-maximized;--remote-allow-origins=*

