Feature: Prueba de carga con multiples usuarios
  Como equipo de QA
  Quiero ejecutar pruebas con multiples usuarios en paralelo
  Para validar el comportamiento bajo carga

  # Este feature crea 50 escenarios independientes
  # Cada escenario usara un usuario diferente del pool (BOT01-BOT50)
  # Se ejecutan en paralelo segun la configuracion de maxParallelForks

  Scenario Outline: Test de caso express - Usuario <id>
    Given el actor tiene un navegador disponible
    When abre la pagina de casos
    And realiza login con credenciales
    And navega a agent
    And diligencia caso express completo desde feature
      | departamento_solicita | municipio_solicita | servicios_especiales | gestor_coordinacion | linea   | servicio   |
      | AMAZONAS              | ARARA              | NO                   | NO                  | <linea> | <servicio> |
    And diligenciamos el proveedor
      | Nombre del proveedor | Servicio      |
      | PROVEEDOR PRUEBA     | TOMA SERVICIO |
    And transicionamos los estados del caso

    Examples:
      | id  | linea             | servicio           |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 02  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 03  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 04  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 05  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 06  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 07  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 08  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 09  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 10  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 11  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 12  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 13  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 14  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 15  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 16  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 17  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 18  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 19  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 20  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 21  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 22  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 23  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 24  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 25  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 26  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 27  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 28  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 29  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 30  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 31  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 32  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 33  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 34  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 35  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 36  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 37  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 38  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 39  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 40  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 41  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 42  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 43  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 44  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 45  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 46  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 47  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 48  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 49  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 50  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |
      | 01  | CONDUCTOR ELEGIDO | CONDUCTOR ELEGIDO |

